steps:
# O passo abaixo executa o mesmo comando 'docker build' que você estava usando.
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t'
    # Use exatamente a mesma URL de destino da sua imagem
    - 'southamerica-east1-docker.pkg.dev/affable-grin-477621-f0/projetollm/app:$COMMIT_SHA'
    - '-f'
    - 'Dockerfile'
    - '.'

# Configura a imagem final que será enviada ao Artifact Registry
images:
- 'southamerica-east1-docker.pkg.dev/affable-grin-477621-f0/projetollm/app:$COMMIT_SHA'

# ESTA É A CORREÇÃO:
# A opção 'logging: CLOUD_LOGGING_ONLY' resolve o erro (Opção C)
options:
  logging: CLOUD_LOGGING_ONLY
