steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build','-t','southamerica-east1-docker.pkg.dev/affable-grin-477621-f0/projetollm/app:latest','.']
images:
  - 'southamerica-east1-docker.pkg.dev/affable-grin-477621-f0/projetollm/app:latest'
options:
  logging: CLOUD_LOGGING_ONLY
