steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    # Primeira tag: com o SHA do commit
    - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/projetollm/app:$COMMIT_SHA'
    - '-t'
    # Segunda tag: com "latest"
    - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/projetollm/app:latest'
    - '-f'
    - 'Dockerfile'
    - '.'

images:
# O Cloud Build automaticamente empurra as imagens listadas aqui
- 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/projetollm/app:$COMMIT_SHA'
- 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/projetollm/app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
