steps:
  - name: gcr.io/cloud-builders/npm
    dir: frontend
    args: ['ci']
  - name: gcr.io/cloud-builders/npm
    dir: frontend
    args: ['run','build']
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args: ['-c','mkdir -p static && rm -rf static/* && cp -r frontend/dist/* static/']
  - name: gcr.io/cloud-builders/docker
    args: ['build','-t','southamerica-east1-docker.pkg.dev/affable-grin-477621-f0/projetollm/app:latest','.']
images:
  - 'southamerica-east1-docker.pkg.dev/affable-grin-477621-f0/projetollm/app:latest'
options:
  logging: CLOUD_LOGGING_ONLY
